### ISSUE TITLE
File not found on guard init rdoc

### ISSUE THREAD

**Issue by deogracia** [bspaulding/guard-rdoc#1]
Hi,
Version : 
- rvm 1.25.28
- guard 2.6.1
- guard-rdoc 1.0.2

I'm starting to use guard and guard-rdoc.
When I run "guard init rdoc" or "guard init" (does the same prefixed with bundle)

```
14:18:40 - INFO - Writing new Guardfile to /home/__USERNAME__/Travail/infra-admin-tools/branches/admin-tools/Guardfile
/home/__USERNAME__/.rvm/gems/ruby-2.1.2@admin-tools/gems/guard-2.6.1/lib/guard/plugin/base.rb:53:in `read': No such file or directory @ rb_sysopen - /home/__USERNAME__/.rvm/gems/ruby-2.1.2@admin-tools/gems/guard-rdoc-1.0.2/lib/guard/rdoc/templates/Guardfile (Errno::ENOENT)
    from /home/__USERNAME__/.rvm/gems/ruby-2.1.2@admin-tools/gems/guard-2.6.1/lib/guard/plugin/base.rb:53:in `template'
    from /home/__USERNAME__/.rvm/gems/ruby-2.1.2@admin-tools/gems/guard-2.6.1/lib/guard/plugin_util.rb:129:in `block in add_to_guardfile'
    from /home/__USERNAME__/.rvm/gems/ruby-2.1.2@admin-tools/gems/guard-2.6.1/lib/guard/plugin_util.rb:126:in `open'
    from /home/__USERNAME__/.rvm/gems/ruby-2.1.2@admin-tools/gems/guard-2.6.1/lib/guard/plugin_util.rb:126:in `add_to_guardfile'
    from /home/__USERNAME__/.rvm/gems/ruby-2.1.2@admin-tools/gems/guard-2.6.1/lib/guard/guardfile/generator.rb:62:in `initialize_template'
    from /home/__USERNAME__/.rvm/gems/ruby-2.1.2@admin-tools/gems/guard-2.6.1/lib/guard/guardfile/generator.rb:88:in `block in initialize_all_templates'
    from /home/__USERNAME__/.rvm/gems/ruby-2.1.2@admin-tools/gems/guard-2.6.1/lib/guard/guardfile/generator.rb:88:in `each'
    from /home/__USERNAME__/.rvm/gems/ruby-2.1.2@admin-tools/gems/guard-2.6.1/lib/guard/guardfile/generator.rb:88:in `initialize_all_templates'
    from /home/__USERNAME__/.rvm/gems/ruby-2.1.2@admin-tools/gems/guard-2.6.1/lib/guard/guardfile.rb:39:in `initialize_all_templates'
    from /home/__USERNAME__/.rvm/gems/ruby-2.1.2@admin-tools/gems/guard-2.6.1/lib/guard/cli.rb:173:in `init'
    from /home/__USERNAME__/.rvm/gems/ruby-2.1.2@admin-tools/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /home/__USERNAME__/.rvm/gems/ruby-2.1.2@admin-tools/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /home/__USERNAME__/.rvm/gems/ruby-2.1.2@admin-tools/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /home/__USERNAME__/.rvm/gems/ruby-2.1.2@admin-tools/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /home/__USERNAME__/.rvm/gems/ruby-2.1.2@admin-tools/gems/guard-2.6.1/bin/guard:6:in `<top (required)>'
    from /home/__USERNAME__/.rvm/gems/ruby-2.1.2@admin-tools/bin/guard:23:in `load'
    from /home/__USERNAME__/.rvm/gems/ruby-2.1.2@admin-tools/bin/guard:23:in `<main>'
    from /home/__USERNAME__/.rvm/gems/ruby-2.1.2@admin-tools/bin/ruby_executable_hooks:15:in `eval'
    from /home/__USERNAME__/.rvm/gems/ruby-2.1.2@admin-tools/bin/ruby_executable_hooks:15:in `<main>'

```

Here's the content of ''/home/**USERNAME**/.rvm/gems/ruby-2.1.2@admin-tools/gems/guard-rdoc-1.0.2/lib/guard/''

```
/home/__USERNAME__/.rvm/gems/ruby-2.1.2@admin-tools/gems/guard-rdoc-1.0.2/lib/guard/
├── rdoc
│   └── version.rb
└── rdoc.rb

```

I tried an other plugin (guard-rubocop) and got no problem.

I found this [issue](https://github.com/kanzeon/guard-mocha-node/issues/9) with an other guard plugin

Thanks

**Comment by deogracia** [comment]
It seems the ''template'' method have to be redefine in this plugin

```
        # Specify the source for the Guardfile template.
        # Each Guard plugin can redefine this method to add its own logic.
        #
        # @param [String] plugin_location the plugin location
        #
        def template(plugin_location)
          File.read("#{ plugin_location }/lib/guard/#{ non_namespaced_name }/templates/Guardfile")
        end
```

What should be in the template file ?
